/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Call {
  'status' : CallStatus,
  'offer' : [] | [string],
  'answer' : [] | [string],
  'callee' : Principal,
  'caller' : Principal,
  'callerIceCandidates' : Array<string>,
  'calleeIceCandidates' : Array<string>,
}
export type CallStatus = { 'initiated' : null } |
  { 'answered' : null } |
  { 'ended' : null };
export interface Feedback {
  'comment' : string,
  'sessionId' : bigint,
  'rating' : bigint,
}
export interface ScheduledSession {
  'id' : bigint,
  'duration' : bigint,
  'scheduledTime' : bigint,
  'host' : Principal,
  'isActive' : boolean,
  'participant' : [] | [Principal],
  'joined' : boolean,
}
export interface UserProfile {
  'credits' : bigint,
  'name' : string,
  'feedback' : Array<Feedback>,
  'skills' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addIceCandidate' : ActorMethod<[bigint, string], undefined>,
  'answerCall' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createUserProfile' : ActorMethod<[string, Array<string>], undefined>,
  'endCall' : ActorMethod<[bigint], undefined>,
  'getActiveCall' : ActorMethod<[], [] | [Call]>,
  'getAvailableScheduledSessions' : ActorMethod<[], Array<ScheduledSession>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserScheduledSessions' : ActorMethod<[], Array<ScheduledSession>>,
  'initiateCall' : ActorMethod<[Principal, string], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinScheduledSession' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'scheduleSession' : ActorMethod<[bigint, bigint], bigint>,
  'startSession' : ActorMethod<[], bigint>,
  'submitFeedback' : ActorMethod<[bigint, bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];