/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CallStatus = IDL.Variant({
  'initiated' : IDL.Null,
  'answered' : IDL.Null,
  'ended' : IDL.Null,
});
export const Call = IDL.Record({
  'status' : CallStatus,
  'offer' : IDL.Opt(IDL.Text),
  'answer' : IDL.Opt(IDL.Text),
  'callee' : IDL.Principal,
  'caller' : IDL.Principal,
  'callerIceCandidates' : IDL.Vec(IDL.Text),
  'calleeIceCandidates' : IDL.Vec(IDL.Text),
});
export const ScheduledSession = IDL.Record({
  'id' : IDL.Nat,
  'duration' : IDL.Nat,
  'scheduledTime' : IDL.Int,
  'host' : IDL.Principal,
  'isActive' : IDL.Bool,
  'participant' : IDL.Opt(IDL.Principal),
  'joined' : IDL.Bool,
});
export const Feedback = IDL.Record({
  'comment' : IDL.Text,
  'sessionId' : IDL.Nat,
  'rating' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'credits' : IDL.Nat,
  'name' : IDL.Text,
  'feedback' : IDL.Vec(Feedback),
  'skills' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addIceCandidate' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'answerCall' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createUserProfile' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'endCall' : IDL.Func([IDL.Nat], [], []),
  'getActiveCall' : IDL.Func([], [IDL.Opt(Call)], ['query']),
  'getAvailableScheduledSessions' : IDL.Func(
      [],
      [IDL.Vec(ScheduledSession)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserScheduledSessions' : IDL.Func(
      [],
      [IDL.Vec(ScheduledSession)],
      ['query'],
    ),
  'initiateCall' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinScheduledSession' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'scheduleSession' : IDL.Func([IDL.Int, IDL.Nat], [IDL.Nat], []),
  'startSession' : IDL.Func([], [IDL.Nat], []),
  'submitFeedback' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CallStatus = IDL.Variant({
    'initiated' : IDL.Null,
    'answered' : IDL.Null,
    'ended' : IDL.Null,
  });
  const Call = IDL.Record({
    'status' : CallStatus,
    'offer' : IDL.Opt(IDL.Text),
    'answer' : IDL.Opt(IDL.Text),
    'callee' : IDL.Principal,
    'caller' : IDL.Principal,
    'callerIceCandidates' : IDL.Vec(IDL.Text),
    'calleeIceCandidates' : IDL.Vec(IDL.Text),
  });
  const ScheduledSession = IDL.Record({
    'id' : IDL.Nat,
    'duration' : IDL.Nat,
    'scheduledTime' : IDL.Int,
    'host' : IDL.Principal,
    'isActive' : IDL.Bool,
    'participant' : IDL.Opt(IDL.Principal),
    'joined' : IDL.Bool,
  });
  const Feedback = IDL.Record({
    'comment' : IDL.Text,
    'sessionId' : IDL.Nat,
    'rating' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'credits' : IDL.Nat,
    'name' : IDL.Text,
    'feedback' : IDL.Vec(Feedback),
    'skills' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addIceCandidate' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'answerCall' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createUserProfile' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'endCall' : IDL.Func([IDL.Nat], [], []),
    'getActiveCall' : IDL.Func([], [IDL.Opt(Call)], ['query']),
    'getAvailableScheduledSessions' : IDL.Func(
        [],
        [IDL.Vec(ScheduledSession)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserScheduledSessions' : IDL.Func(
        [],
        [IDL.Vec(ScheduledSession)],
        ['query'],
      ),
    'initiateCall' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinScheduledSession' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'scheduleSession' : IDL.Func([IDL.Int, IDL.Nat], [IDL.Nat], []),
    'startSession' : IDL.Func([], [IDL.Nat], []),
    'submitFeedback' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };